services:
    beetrigged:
        env_file: .env
        build:
            context: ./BeeTriggered
            dockerfile: Dockerfile
        volumes:
            - ./OpenCanary/data/:/test/
        depends_on:
            - opencanary
        restart: always

    opencanary:
        env_file: .env
        network_mode: 'host'
        cap_add:
            - NET_ADMIN
        build:
            context: ./OpenCanary/
            dockerfile: Dockerfile.stable
        restart: always
        volumes:
            - ./OpenCanary/data/:/root/
