services:
    beetrigged:
        environment:
            - WEBSITE=${WEBSITE}
            - LOG_API=${LOG_API}
            - MACHINE_ID=${MACHINE_ID}
            - PUBLIC_API_KEY=${PUBLIC_API_KEY}
            - SECRET_API_KEY=${SECRET_API_KEY}
            - TZ=${TZ}
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - opencanary/data/:/test/
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - opencanary
        restart: always

    opencanary:
        environment:
            - WEBSITE=${WEBSITE}
            - LOG_API=${LOG_API}
            - MACHINE_ID=${MACHINE_ID}
            - PUBLIC_API_KEY=${PUBLIC_API_KEY}
            - SECRET_API_KEY=${SECRET_API_KEY}
            - TZ=${TZ}
        network_mode: 'host'
        cap_add:
            - NET_ADMIN
        build:
            context: opencanary/
            dockerfile: Dockerfile.stable
        restart: always
        volumes:
            - opencanary/data/.opencanary.conf:/root/.opencanary.conf
            - /var/log/kern.log:/var/log/kern.log
